### ISSUE TITLE
Error when a == b or b == 0 in FortranRecordWriter('Fa.b') 

### ISSUE THREAD

**Issue by Kayya886** [brendanarnold/py-fortranformat#18]
```python
import fortranformat as ff
reader = ff.FortranRecordReader('F5.5')
writer = ff.FortranRecordWriter('F5.5')
reader.read('123456')  # result: [0.12345]
writer.write([0.12345])  # result: '*****' 
```

**Comment by brendanarnold** [comment]
Hi @Kayya886 

Fortran formats are not symmetric - valid read formats are not always valid write formats

In this case, the write format is invalid - you have asked for 5 decimal places plus a `.` character in 5 spaces which is impossible!
