### ISSUE TITLE
write function adds '\n'?

### ISSUE THREAD

**Issue by zhengyang-c** [brendanarnold/py-fortranformat#19]
Greetings,

I'm not familiar with Fortran at all, but when using the following format:

```python
>>> import fortranformat as ff
>>> header_line = ff.FortranRecordWriter('(a4,f7.4,a1,1x,f8.4,a1,1x,i4,1x,i1,1x,i3,1x,f5.2,2x,f5.2)')
>>> header_line.write(["TA19", 5.4, "N", 94.2, "E", 100, 1, 1, 0, 0, 1])
'TA19 5.4000N  94.2000E  100 1   1  0.00   0.00\n   1'
```

I see that I obtain a '\n' in the output. I was hoping you could shed some light on how the module decides or not to add a line break.

Thank you!

**Comment by brendanarnold** [comment]
Hi, its because you have specified a format with 10 printing edit descriptors (`x` is non printing) and supplied 11 values. The 11th value starts a new record/row. This is part of the FORTRAN spec.

**Comment by zhengyang-c** [comment]
Oh, I see! Thank you so much! I did not notice.
