### ISSUE TITLE
Cut-down test suite?

### ISSUE THREAD

**Issue by alexmalins** [brendanarnold/py-fortranformat#25]
Hi Brendan,

Thanks for publishing this package - it's been a life-saver for me multiple times over the past few years.

Recently I worked on updating the fortranformat conda-forge [feedstock](https://anaconda.org/conda-forge/fortranformat). As best practice it would be good to add running the package tests to the feedstock recipe, however the default test suite is super comprehensive and takes too long to run on the CI infrastructure.

Is it possible to include a `runminimaltests` option in the Makefile for running a minimal selection of the tests, while still checking the core functionality of this package? Or can you think of another way of running a quicker version of the test suite?

Happy to help contribute to this if you'd appreciate some another pair of hands !

**Comment by brendanarnold** [comment]
Firstly thanks for including `fortranformat` in feedstock - its much appreciated!

Secondly, yes I will look into a `runminimaltests` option - it might be a case of running just te handwritten tests and the first 100 tests for each edit descriptor. I'll put that together and add you as reviewer.

**Comment by alexmalins** [comment]
Sounds great, thanks !

**Comment by brendanarnold** [comment]
Hey @alexmalins here is the PR https://github.com/brendanarnold/py-fortranformat/pull/26

Went down to 10 tests per file which still leaves over a thousand tests but cover a wide range of edit descriptor combinations.

The minimal tests still need to be built after initial clone which takes a few seconds with `make buildtests` - let me know if this causes trouble for pipeline integration and I can check the minimal tests into source

I'll hold off merging until I hear back

**Comment by alexmalins** [comment]
Thanks! I think running `make buildtests` then `make runminimaltests` should be no issue for the conda-forge pipeline integration.
