### ISSUE TITLE
Error handling np.NaN 

### ISSUE THREAD

**Issue by Lunyxis** [brendanarnold/py-fortranformat#28]
Hi, 

The variable "_ed_" is not defined in : _output.py -> _compose_float_string()

```
# handle the nan and inf cases
if type(val) is float and val != val:
        return _compose_nan_string(w, ed)
Infinity = 1e1000000
if val in (-Infinity, Infinity):
    return _compose_inf_string(w, ed, sign_bit)
```

I suppose that instead of "_ed_", we must use "_ftype_".

Great work by the way :)

**Comment by brendanarnold** [comment]
Thanks for raising - and for compliments :) I've replicated the bug, written some tests and released a fix (v1.2.2). See PR #29 for code.
