### ISSUE TITLE
Run tests on release

### ISSUE THREAD

**Issue by dschwoerer** [brendanarnold/py-fortranformat#32]
I am trying to package fortranformat for fedora, however I cannot run the tests for the pypi archives, as the Makefile is not included.

Also, there are no tags or releases on github, thus I cannot simply take a tarball from here.

Could you please tag your versions or provide some other mechanism to get releases with the bits for testing?

**Comment by brendanarnold** [comment]
Hi, thanks for maintaining the package, it's really appreciated.

I put source release in the `dist` folder. Do they need to be explicitly tagged? Do you need a `.whl` binary release as well?

**Comment by dschwoerer** [comment]
A tag would be super useful :-)

https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

I do not need anything in the `dist/` folder (I have never seen that folder being tracked by git), just a tag for the version that ends up being released. https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository is a documentation on how to add tags.

**Comment by brendanarnold** [comment]
Hi @dschwoerer I've included tags now. Please beware that running tests for older versions might not be easy or even possible. I had taken an approach where I wrote a script to auto-generate python test files for, frankly, too many variations of FORTRAN edit descriptors. This got a bit unwieldy and often the test suite wouldn't complete. If I remember correctly I was able to run the tests in batches using the test runner and/or only generating a subset of tests at a time however doing the whole suite in one go tended to freeze up.

More recent versions having a `make runminimaltests` command which are more targeted and written by hand. I would recommend running that where available instead.

I realise this isn't ideal - please let me know if there is anything I can do to make life a bit easier

**Comment by dschwoerer** [comment]
Thanks :100: 

That resolves my issue.

I will open a different issue about the failing tests.

The minimal / hand written tests all pass, thus I guess that is sufficient.
I do not intend to run the old tests or on old version, but mostly to ensure that fortranformat works well with the packages in fedora.
