### ISSUE TITLE
Deprecated install method

### ISSUE THREAD

**Issue by tbody-cfs** [brendanarnold/py-fortranformat#38]
Super useful project - thanks for developing this!

When installing `fortranformat` into another Python project, I get the following deprecation warning
```
DEPRECATION: fortranformat is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

Should I prepare a PR adding a `pyproject.toml`? Happy to make this with a go-ahead.

**Comment by brendanarnold** [comment]
Yes please, I’m not familiar with the new approach so it would save me a lot of time

**Comment by tbody-cfs** [comment]
I've had a go in #39. I also added Github actions to automatically run pytest and instructions in case you want to also let this workflow push to Github Actions
